### ISSUE TITLE
Move "Thieves of Sesame Street" to Compression or Analysis

### ISSUE THREAD

**Issue by martiansideofthemoon** [thunlp/PLMpapers#15]
Hi,
I'm the first author of a paper mentioned in this list, "Thieves on Sesame Street! Model Extraction of BERT-based APIs". Firstly, thanks so much for the mention!

I feel the paper might be more appropriate under the **Knowledge Distillation & Model Compression** section or the **Analysis** section, since it's not really a new model.

**Comment by zzy14** [comment]
Fixed. Thanks for your suggestion!
